apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secrets-role
rules:
- apiGroups:
  - "*"
  resources:
  - secrets
  - jobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-secrets-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-secrets-role
subjects:
- kind: ServiceAccount
  name: default
